image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache curl jq python3 py-pip
  - pip install awscli

stages:
  - build

build:
  image: docker:stable
  stage: build
  script:
    - IMAGE_TAG="$CI_COMMIT_SHA"
    - $(aws ecr get-login --no-include-email --region ap-northeast-2)
    - ECR_BASE_URI=528064768589.dkr.ecr.ap-northeast-2.amazonaws.com

    - PEDMAX_REPOSITORY_URI=$ECR_BASE_URI/pedmax-production-backend
    - docker build . -t $PEDMAX_REPOSITORY_URI:latest -t $PEDMAX_REPOSITORY_URI:$IMAGE_TAG 
    - docker push $PEDMAX_REPOSITORY_URI:latest
    - docker push $PEDMAX_REPOSITORY_URI:$IMAGE_TAG

  only:
    - pedmax_production
    
  tags:
    - docker
