AllCops:
  Exclude:
  # Rubocop defaults
  - Gemfile
  - vendor/**/*
  - spec/fixtures/**/*
  - tmp/**/*
  # Framework generated configuration files
  - config/boot.rb
  - config/application.rb
  - config/environment.rb
  - config/puma.rb
  - config/spring.rb
  - config/environments/development.rb
  - config/environments/production.rb
  - config/environments/staging.rb
  - config/environments/test.rb
  - config/initializers/application_controller_renderer.rb
  - config/initializers/assets.rb
  - config/initializers/backtrace_silencers.rb
  - config/initializers/cookies_serializer.rb
  - config/initializers/cors.rb
  - config/initializers/filter_parameter_logging.rb
  - config/initializers/inflections.rb
  - config/initializers/mime_types.rb
  - config/initializers/new_framework_defaults.rb
  - config/initializers/session_store.rb
  - config/initializers/wrap_parameters.rb
  - config/initializers/devise.rb
  - config/initializers/sidekiq.rb
  - config/initializers/doorkeeper.rb
  - test/application_system_test_case.rb
  - test/test_helper.rb
  - bin/**/*
  - script/**/*
  - db/schema.rb
  # Other generated files (project independent)
  - spec/spec_helper.rb
  - spec/rails_helper.rb
  - lib/omniauth/strategies/*
